[WIP]chatspace画面の実装
yoshidakai1998/chat-space pull request #3
Opened 2018-12-27 04:51 UTC by yoshidakai1998

# What
チャット画面を実装する
# Why 
ChatSpaceアプリのメイン画面となるため。

2019-01-05 06:37 UTC, takebn26 commented on Gemfile
>  gem 'erb2haml'
[MUST] こちらdevelopment環境でしか使わないgemなのでgroup development以下に入れましょう

2019-01-05 06:37 UTC, takebn26 commented on app/controllers/messages_controller.rb
> +def index
[IMO] インデントずらしましょう

2019-01-05 06:39 UTC, takebn26 commented
こちら仮の画面作成でしょうか？
このpull requestでメイン画面のscssに当たるものが見当たらないため
でなければ、scss作ってしまいましょう

2019-01-05 06:46 UTC, takebn26 commented on Gemfile
>  gem 'erb2haml'
[MUST] development環境で使うのはこちらのgemだけですね
```
gem 'erb2haml'
```

2019-01-05 06:54 UTC, yoshidakai1998 commented
gemfileとインデントの修正をしました！
仮の画面作成です。
これからscssの実装をしたいと思います！

2019-01-05 07:00 UTC, takebn26 commented
LGTMです！

2019-01-12 05:47 UTC, ta910 commented on app/assets/stylesheets/application.scss
> +@import "./reset";
こちらのファイル、インデントが4つになっていますが、2つに修正しましょう

2019-01-12 05:47 UTC, ta910 commented
画面を作った際はスクリーンショットを貼りましょう

2019-01-12 05:47 UTC, ta910 commented
wipを外してからPRを出しましょう！

2019-01-14 02:57 UTC, yoshidakai1998 commented
<h2>チャット画面のスクリーンショットです</h2>

![unadjustednonraw_thumb_43](https://user-images.githubusercontent.com/45656356/51094793-53af4d00-17f3-11e9-9a54-c71ac02a194b.jpg)

2019-01-14 03:03 UTC, takebn26 requested changes

2019-01-14 03:03 UTC, takebn26 commented on app/views/messages/index.html.haml
> +          = link_to '/groups/001/messages' do
まだルーティングが設定されていないときは '#'と仮のパスを当てておくのが慣習です

2019-01-14 03:03 UTC, takebn26 commented on app/views/messages/index.html.haml
> +
こちらから下は不要であれば消しましょう

2019-01-14 03:03 UTC, takebn26 commented on app/assets/stylesheets/_clearfix.scss
> +}
下に空行一つ足しましょう

2019-01-14 06:44 UTC, yoshidakai1998 commented
修正しました

2019-01-14 06:46 UTC, kuroko918 commented on app/assets/stylesheets/application.scss
> +.notification {
application.scssにはimport以外は記述しないようにしましょう！
この行以下の記述は外部SCSSファイルを作成し、application.scssでimportしましょう！

2019-01-14 06:46 UTC, kuroko918 commented on app/assets/stylesheets/application.scss
> +// }
こちらのコメントは使用しますか？

2019-01-14 06:46 UTC, kuroko918 commented on config/routes.rb
>    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
こちらのコメントは消しましょう！

2019-01-14 06:54 UTC, yoshidakai1998 commented on app/assets/stylesheets/application.scss
> +.notification {
了解しました

2019-01-14 06:54 UTC, yoshidakai1998 commented on app/assets/stylesheets/application.scss
> +// }
使用しませんので、削除しました

2019-01-14 06:55 UTC, yoshidakai1998 commented on config/routes.rb
>    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
了解しました

2019-01-14 06:57 UTC, yoshidakai1998 commented
ご指摘いただいた箇所を修正しました。

2019-01-14 07:03 UTC, kuroko918 commented on app/assets/stylesheets/application.scss
> +@import "chat-main.scss"
.scssは不要なので消しておきましょう！

2019-01-14 07:06 UTC, yoshidakai1998 commented on app/assets/stylesheets/application.scss
> +@import "chat-main.scss"
修正しました

2019-01-14 07:10 UTC, takebn26 commented
LGTMです！マージして次に行きましょう！

2019-01-14 07:16 UTC, yoshidakai1998 commented
了解です！

2019-01-14 07:16 UTC, merged