ユーザー管理機能の実装
yoshidakai1998/chat-space pull request #4
Opened 2019-01-15 06:41 UTC by yoshidakai1998

Initial commit

2019-01-17 07:07 UTC, takebn26 requested changes

2019-01-17 07:07 UTC, takebn26 commented on app/assets/stylesheets/application.scss
>  @import "./_variable";
```
"./_variable" → "./variable"
```

2019-01-17 07:07 UTC, takebn26 commented on app/controllers/users_controller.rb
> +class UsersController < ApplicationController
インデントは二つに統一しましょう

2019-01-17 07:07 UTC, takebn26 commented on app/views/messages/index.html.haml
> +            =current_user.name
= のあとは必ず半角スペース入れましょう
見易さは常に重視しましょう

2019-01-17 07:07 UTC, takebn26 commented on app/assets/stylesheets/user.scss
> +    h2 {
要素に対してcss当てるのではなく出来るだけクラスをつけてあげましょう

2019-01-18 06:57 UTC, hirozak commented on app/controllers/users_controller.rb
> +end
このファイルのインデントがおかしいので修正しましょう

2019-01-18 07:02 UTC, yoshidakai1998 commented on app/controllers/users_controller.rb
> +end
修正しました

2019-01-18 07:05 UTC, ShuheiTsuji commented on app/assets/stylesheets/_variable.scss
> +$alert_orange: #F35500;
最後には空行を追加しましょう

2019-01-18 07:05 UTC, ShuheiTsuji commented on app/assets/stylesheets/application.scss
> +@import "flash";
ここも

2019-01-18 07:05 UTC, ShuheiTsuji commented on app/assets/stylesheets/flash.scss
> +  	background-color: $lightblue;
インデントが気になりますね

2019-01-18 07:05 UTC, ShuheiTsuji commented on app/assets/stylesheets/user.scss
> +    .field-label {
省略記法使えるところは使いましょう！

2019-01-18 07:05 UTC, ShuheiTsuji commented on app/controllers/users_controller.rb
> +class UsersController < ApplicationController
この修正確認しましょう

2019-01-18 07:05 UTC, ShuheiTsuji commented on app/controllers/users_controller.rb
> +end
この修正確認しましょう

2019-01-18 07:05 UTC, ShuheiTsuji commented on app/controllers/users_controller.rb
> +end
インデント4つになっているので、ご自身でgithub上にて確認し修正してください！

2019-01-18 15:22 UTC, yoshidakai1998 commented on app/assets/stylesheets/flash.scss
> +  	background-color: $lightblue;
ご指摘ありがとうございます！
どの辺のインデントのことですか？

2019-01-18 15:22 UTC, yoshidakai1998 commented on app/assets/stylesheets/user.scss
> +    .field-label {
ご指摘ありがとうございます！
どのように省略記法を使用すれば良いのですか？

2019-01-19 05:55 UTC, ghost requested changes

2019-01-19 05:55 UTC, hiroki5123 commented on config/locales/ja.yml
> +    pm: 午後
最後に空行いれてください。

2019-01-19 05:55 UTC, hiroki5123 commented on app/views/layouts/_notifications.html.haml
> +    = content_tag :div, value, class: key
最後に空行いれてください。

2019-01-19 06:00 UTC, yoshidakai1998 commented on config/locales/ja.yml
> +    pm: 午後
修正しました

2019-01-19 06:00 UTC, yoshidakai1998 commented on app/views/layouts/_notifications.html.haml
> +    = content_tag :div, value, class: key
修正しました

2019-01-19 06:01 UTC, yuki-uchida commented
前回へのコメントへの対応を記述することは徹底するようお願いいたします

2019-01-19 06:03 UTC, yoshidakai1998 commented on app/assets/stylesheets/_variable.scss
> +$alert_orange: #F35500;
修正しました

2019-01-19 06:03 UTC, yoshidakai1998 commented on app/assets/stylesheets/application.scss
> +@import "flash";
修正しました

2019-01-19 06:03 UTC, yoshidakai1998 commented on app/controllers/users_controller.rb
> +end
修正しました

2019-01-19 06:04 UTC, yoshidakai1998 commented on app/views/messages/index.html.haml
> +            =current_user.name
修正しました

2019-01-19 06:04 UTC, yoshidakai1998 commented on app/assets/stylesheets/application.scss
>  @import "./_variable";
修正しました

2019-01-19 06:05 UTC, yuki-uchida requested changes

2019-01-19 06:05 UTC, yuki-uchida commented on app/assets/stylesheets/user.scss
> +    h2 {
.account-page {
   .account-page__inner {
などは、親要素の名前を引き継いで、
.account-page {
   &__inner {
のように、&(アンバサンド)を使って省略できます。調べて見てください

2019-01-19 06:05 UTC, yuki-uchida commented on app/views/devise/sessions/new.html.haml
> +          .field
こちら、.filedの中に.fieldが入っていて、少し見づらいですね。同じクラス名は使用しない方がいいでしょう

2019-01-19 06:17 UTC, yoshidakai1998 commented on app/assets/stylesheets/flash.scss
> +  	background-color: $lightblue;
修正しました

2019-01-19 06:19 UTC, yoshidakai1998 commented on app/assets/stylesheets/user.scss
> +    .field-label {
修正しました

2019-01-19 06:22 UTC, yoshidakai1998 commented on app/views/devise/sessions/new.html.haml
> +          .field
修正しましたが、合っているか自信がないのでご確認お願いします。

2019-01-19 06:25 UTC, yuki-uchida approved these changes
LGTMです。面倒とは思いますが、頂いたコメントには一つ一つ行った対応を記述するようにお願い致します。
お疲れ様でした

2019-01-19 06:25 UTC, yuki-uchida commented on app/assets/stylesheets/user.scss
> +    h2 {
いいですね！

2019-01-19 06:33 UTC, yoshidakai1998 commented
丁寧な対応ありがとうございます！
以後、一つ一つのコメントに行った改善を記述するようにしていきたいと思います！

2019-01-19 06:35 UTC, merged